* [32majustes-de-lobby[m
  fase-1-mvp[m
  feat/chat[m
  feat/frontend-modal[m
  feat/frontend-tabuleiro[m
  feat/gameserver[m
  feat/interface-inicial[m
  feat/modal-inicio-partida[m
  feat/mundanca-tabuleiro[m
  feat/pubsub-escalabilidade[m
  feat/redis[m
  feat/servidor[m
  fix/correcao-frontend[m
  gerenciar-salas[m
  main[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/ajustes-de-lobby[m
  [31mremotes/origin/correcoes-de-sala[m
  [31mremotes/origin/develop[m
  [31mremotes/origin/fase-1-mvp[m
  [31mremotes/origin/feat/chat[m
  [31mremotes/origin/feat/gameserver[m
  [31mremotes/origin/feat/interface-inicial[m
  [31mremotes/origin/feat/modal-inicio-partida[m
  [31mremotes/origin/feat/mundanca-tabuleiro[m
  [31mremotes/origin/feat/pubsub-escalabilidade[m
  [31mremotes/origin/feat/reconexao[m
  [31mremotes/origin/feat/redis[m
  [31mremotes/origin/feat/servidor[m
  [31mremotes/origin/gerenciar-salas[m
  [31mremotes/origin/main[m
  [31mremotes/origin/pagina-explicacao[m
  [31mremotes/origin/tela-inicial-jogo[m
